# Autenticación

### Registro de usuario 
POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
  "name": "Nuevo Usuario",
  "email": "nuevo.usuario@example.com",
  "phone": "12345678",
  "role": "user"
}

### Inicio de sesión
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "email": "nuevo.usuario@example.com",
  "password": "nuevaPasswordSegura"
}

### Cambio de contraseña 
# Este endpoint requiere que el usuario esté autenticado. Nota: Usar el token JWT obtenido del login
PATCH http://localhost:3000/api/auth/set-password
Content-Type: application/json
Authorization: Bearer TOKEN_JWT

{
  "old_password": "1234",
  "new_password": "nuevaPasswordSegura",
  "confirm_password": "nuevaPasswordSegura"
}




# Publicaciones

### Listar todas las publicaciones con paginación
# Esta ruta es pública y no requiere autenticación.
# Para paginación, usar los parámetros `page` y `limit` pagina por defecto 1 y límite 10.
GET http://localhost:3000/api/publicaciones?page=1&limit=10

### Ver una publicación específica
# Esta ruta es pública y no requiere autenticación. Nota: Usar un ID de publicación existente
GET http://localhost:3000/api/publicaciones/ID_PUBLICACION 

### Crear una nueva publicación
# Requiere que el usuario esté autenticado. Nota: Usar el token JWT obtenido del login
POST http://localhost:3000/api/publicaciones
Content-Type: application/json
Authorization: Bearer TOKEN_JWT

{
  "titulo": "Mi Primera Publicación de Blog 5",
  "contenido": "Este es el contenido de mi primera publicación. ¡Espero que les guste!"
}

### Editar una publicación (solo el autor)
# Requiere autenticación y verificación de propiedad. Nota: Usar el ID de la publicación a editar y Usar el token JWT obtenido del login
PUT http://localhost:3000/api/publicaciones/ID_PUBLICACION
Content-Type: application/json
Authorization: Bearer TOKEN_JWT

{
  "titulo": "Mi Publicación 2 Editada",
  "contenido": "Este es el contenido actualizado de mi publicación. ¡Ahora es mejor!"
}

### Eliminar una publicación (solo el autor)
# Requiere autenticación y verificación de propiedad. Nota: Usar el ID de la publicación a eliminar y Usar el token JWT obtenido del login
DELETE http://localhost:3000/api/publicaciones/ID_PUBLICACION
Authorization: Bearer TOKEN_JWT




# Comentarios

### Ver todos los comentarios de una publicación
# Esta ruta es pública.# Reemplazar con un ID de publicación existente. Nota: Usar el ID de la publicación
GET http://localhost:3000/api/publicaciones/ID_PUBLICACION/comentarios

### Comentar en una publicación
# Requiere que el usuario esté autenticado. Nota: Usar el ID de la publicación a comentar y Usar el token JWT obtenido del login
POST http://localhost:3000/api/publicaciones/ID_PUBLICACION/comentarios
Content-Type: application/json
Authorization: Bearer TOKEN_JWT

{
  "contenido": "¡Excelente publicación! Me ha sido de gran ayuda."
}